# Generated by Django 5.1 on 2024-09-17 07:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0007_remove_news_news_short_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=250)),
                ('sent_date', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='date sent')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welcome.news')),
            ],
        ),
    ]
